name: .NET Nuget Release

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
    - name: Nuget Pack
      run: dotnet pack --no-build --configuration Release
    - name: Nuget Push
      env:
        AUTH_KEY: ${{secrets.NUGET_KEY}}
      run: dotnet nuget push "./bin/Release/UnitSystems.*.nupkg" --api-key "$AUTH_KEY" --source https://api.nuget.org/v3/index.json
