name: Tests

on:
  workflow_dispatch:
jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Secret
    - shell: bash
      env:
        SUPER_SECRET: ${{ secrets.NUGETORG_KEY }}
      run: |
        echo "Sekret: $SUPER_SECRET"
