name: Tests

on:
  workflow_dispatch:
jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Secret
      env:
        SUPER_SECRET: ${{ secrets.NUGET_KEY }}
      run: |
        echo "Sekret: $SUPER_SECRET"
